# This is a basic workflow to help you get started with Actions

name: Test URLS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "testgf-multi-env" branch
  push:
    branches: 'testgf-multi-env'
  pull_request:
    branches: ["testgf-multi-env"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testEndpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

        # Exclude /billing since it requires production environment
      - name: development
        run: |
          for endpoint in $(ls ./routes/pages)
          # start for
          do
              # skip billing in dev
              if [ "$endpoint" != "billing" ]; then
                curl_status=`curl --silent --connect-timeout 8 --output /dev/null https://desp-continuo-211131750-08.herokuapp.com/$endpoint -I -w "%{http_code}\n"`
                  if test $curl_status -ne 200; then
                      echo "$curl_status - https://desp-continuo-211131750-08.herokuapp.com/$endpoint" 
                      exit 1
                  else
                      echo "$curl_status - https://desp-continuo-211131750-08.herokuapp.com/$endpoint"
                  fi # end if $curl_status -ne 200
              fi # end if $endpoint
          # end for
          done
      - name: production
        run: |
          for endpoint in $(ls ./routes/pages)
          do
            curl_status=`curl --silent --connect-timeout 8 --output /dev/null https://prod-211131750-08.herokuapp.com/$endpoint -I -w "%{http_code}\n"`
            if test $curl_status -ne 200; then
              echo "$curl_status - https://prod-211131750-08.herokuapp.com/$endpoint" 
              exit 1
            else
              echo "$curl_status - https://prod-211131750-08.herokuapp.com/$endpoint"
            fi
          done
